name: CI
on: [push]
jobs:
    build:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ["12.x", "14.x"]
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install deps and build (with cache)
              uses: bahmutov/npm-install@v1

            - name: running lint
              run: npm run prettier

            - name: Fix Eslint errors
              run: npm run lint

            - name: running tests
              run: npm run test

            - name: Build
              run: npm run build
            - run: npm publish --access public
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
